### ISSUE TITLE
Make /etc/backuppc a mounted filesystem

### ISSUE THREAD

**Issue by irontoby** [ktwe/docker-backuppc#2]
Hello, thanks so much for making this source available. I'm very new to Docker and was glad to see your approach as I wasn't familiar with using `supervisord` before.

I think it's very convenient to also have `/etc/backuppc` a mounted host volume so I can change my configs without having to ssh into the container. Would this simply involve adding another `VOLUME` command and then using the correct -v option during run?

**Comment by ktwe** [comment]
Yes, exactly.

**Comment by irontoby** [comment]
@ktwe great, thanks for the reply. Guess I'll close the issue since there's really nothing else to it!
